chat/urls.py
from django.conf.urls import url
from . import views

app_name = 'chat'

urlpatterns = [
    url(r'^login/$',views.login, name='login'),
    url(r'^process/$',views.processdata, name ='process'),
    url(r'^show/$',views.show, name = 'shows'),
    url(r'^logout/$',views.logout, name = 'logout'),
    url(r'^show/(?P<user_id1>[0-9]+)/(?P<user_id2>[0-9]+)/messages/$',views.messages, name = "message")
]

chatapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^chat/',include('chat.urls')),
    url(r'^admin/', admin.site.urls),
]

chat/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class user(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    token = models.AutoField(primary_key=True)

class message(models.Model):
    token = models.ForeignKey(user,on_delete=models.CASCADE)
    text = models.CharField(max_length=100)
    rtoken = models.IntegerField(default=0)

class allconnection(models.Model):
    token = models.ForeignKey(user,on_delete=models.CASCADE)
    ctoken = models.IntegerField(default=0)

chat/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from chat.models import user,message,allconnection
from django.urls import reverse
# Create your views here.

def login(request):
    return render(request,'chat/login.html')

def processdata(request):
    username = request.POST['username']
    password = request.POST['password']
    request.session['username'] = username
    loginorsingup = request.POST['choice']
    if loginorsingup=='login':
        accounts = user.objects.all()
        for account in accounts:
            if (account.username == username and account.password == password):
                request.session['token'] = account.token
                return HttpResponseRedirect('../show')
        return render(request,'chat/login.html',{'error_message':'Wrong username/password'})


    else:
        object = user(username,password)
        object.save()
        return HttpResponse("Sing up")


def show(request):
    try:
        username = request.session['username']
        token = request.session['token']
    except:
        return HttpResponseRedirect('../login')
    allaccount = user.objects.all()
    connections = allconnection.objects.all()
    return render(request,'chat/show.html',{'username':username,'token':token,'allaccount':allaccount,'connections':connections})

def logout(request):
    request.session.flush()
    return HttpResponseRedirect('../login')

def messages(request,user_id1,user_id2):
        if (request.POST):
            smessage = request.POST['sentmessage']
            alluser = user.objects.get(token=user_id1)
            object = message(token=alluser,text=smessage,rtoken=user_id2)
            object.save()
            checkconnections = allconnection.objects.all()
            count=0
            for x in checkconnections:
                if (int(user_id1)==x.token.token and int(user_id2)==x.ctoken):
                    count+=1
            if count==0:
                connectionobject = allconnection(token=alluser,ctoken=user_id2)
                connectionobject.save()
            alluser2 = user.objects.get(token=user_id2)
            count=0
            for x in checkconnections:
                if (int(user_id2)==x.token.token and int(user_id1)==x.ctoken):
                    count+=1
            if count==0:
                connectionobject = allconnection(token=alluser2,ctoken=user_id1)
                connectionobject.save()
        allmessage = message.objects.all()
        connections = allconnection.objects.all()
        user_id1 = int(user_id1)
        user_id2 = int(user_id2)
        username = user.objects.get(token=user_id2).username
        return render(request,'chat/message.html',{'user_id1':user_id1,'allmessage':allmessage,'user_id2':user_id2,'user':user,'username':username})

chat/templates/chat/login.html
{% load static %}
<!DOCTYPE html>

<head>
 <script>
   window.location.hash="no-back-button";
   window.location.hash="Again-No-back-button";//again because google chrome don't insert first hash into history
   window.onhashchange=function(){window.location.hash="no-back-button";}
 </script>

<style>
 body{
   background-image : url({% static "chat/candybg.jpg" %});
   background-size: cover;
   background-position: center;
   margin: 0px;
 }
 h1{
   color: rgba(255,140,0,1);
   //color : white;
   font-size: 45px;
   background-color: rgba(255, 255, 255, 0.8);
   border: 2px solid orange;
 }
 .form{
   border : 3px solid #f1f1f1;
   border-color: rgba(255,215,0,0.7);
   margin: 10% 15%;
   background-color: rgba(255,255,255,0.8)
 }
 input[type=text], input[type=password]{
   width : 80%;
   display : inline-block;
   margin: 10px;
   height : 30px;
   background-color: rgba(255,215,0,0.3);
 }
 input[type=submit]{
   width:40%;
   height : 30px;
   background-color: rgba(255,215,0,0.7);
   margin: 5px;
 }
</style>
</head>

<body>

 <center><h1>Candy Chat</h1><center>

 <form action="{% url 'chat:process' %}" method="post" class="form">
  {% csrf_token %}
   <input type="text" name="username" placeholder="username" required="required" pattern="[A-Za-z0-9]{3,20}"/>
   <input type="password" name="password" placeholder="password" required="required" pattern="[A-Za-z0-9]{5,20}"/>
   <input type="submit" name="choice" value="login"/>
  <hr/>
   <input type="submit" name="choice" value="singup"/>
 {% if error_message %}
 <h3>{{error_message}}</h3>
 {% endif %}
 </form>

</body>
</html>

chat/templates/chat/message.html
{% load static %}
<!DOCTYPE html>
<head>
  <!--COMMON ERRORS HANDLING-->
     <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <!--common errors handling-->

  <style>
  body {
    background-image: url({% static "chat/candybg.jpg" %});
  }
  .username{
    font-size: 35px;
    color: rgb(0,191,255);
    margin-left: 5%;
    font-style: italic;
  }
  .messagebox{
    height: 10vh;
  }
  .recieve{
    color:Blue;
    margin-left: 5px;
    font-size: 20px;
  }
  .send{
    color:Green;
    text-align: right;
    margin-right: 5px;
    font-size: 20px;
  }
 .mainbody{
   height : 100vh;
   display: block;
   flex-wrap: nowrap;
   margin: 0 10% 0 10%;
 }
 .upperpart{
   height: 15%;
   width : 100%;
   display: flex;
   flex-wrap: wrap;
   background-color: rgba(255,215,0,0.7);
 }
 .middlepart{
   height : 70%;
   width: 100%;
   overflow-y :  scroll;
   background-color: rgba(0,191,255,0.7);
 }
 .lastpart{
   height: 15%;
   width: 100%;
   background-color: rgba(255,215,0,0.7);
   display: flex;
   align-items: center;
   justify-content: center;
 }
 .leftside{
   width : 62%;
   height : 100%
 }
 .rightside{
   width : 38%;
   height : 100%;
   display: flex;
   align-items: center;
   justify-content: center;
 }
 a{
   text-decoration : none;
   font-size: 25px;
   //color: rgb(0,191,255);
   color : white;
 }
  </style>

  <script>
   window.onload=function () {
       var objDiv = document.getElementsByClassName("middlepart")[0];
       objDiv.scrollTop = objDiv.scrollHeight;
  }
</script>


</head>
<body>

<div class="mainbody">
  <div class="upperpart">
    <div class="leftside">
      <h2 class="username">{{username}}</h2>
    </div>
    <div class="rightside">
      <a href="../../../">Home</a>
    </div>
  </div>
  <div class="middlepart">
    <!--all user start-->
    {% for x in allmessage%}
    {% if x.token.token == user_id1 %}
      {% if x.rtoken == user_id2 %}
      <div class="messagebox">
        <h4 class="send">{{x.text}}</h4>
      </div>
      {% endif %}
    {% else %}
     {% if user_id1 == x.rtoken %}
       {% if x.token.token == user_id2 %}
       <div class="messagebox">
         <h4 class="recieve">{{x.text}}</h4>
       </div>
       {% endif %}
     {% endif %}
    {% endif %}
    {% endfor %}
    <!--all user end-->
  </div>
  <div class="lastpart">
    <form action="" method="post">
    {% csrf_token %}
    <input type="text" id="messageid" name="sentmessage" placeholder="type message"/>
    <input type="submit" value="send"/>
    </form>
  </div>
</div>
</body>
</html>

chat/templates/chat/show.html
{% load static %}
<!DOCTYPE html>
<head>
  <!--COMMON ERRORS HANDLING-->
     <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <!--common errors handling-->

  <style>
  body {
    background-image: url({% static "chat/candybg.jpg" %});
  }
  .mainbody{
    height : 100vh;
    display : block;
    flex-wrap: nowrap;
    background-color: rgba(255,215,0,0.7);
    margin: 0 10% 0 10%;
  }
  .upperpart{
    height : 25%;
    weight : 100%;
    display: flex;
    flex-wrap: wrap;
  }
  .downwardpart{
    height : 75%;
    weight : 100%;
    display: flex;
    flex-wrap: wrap;
  }
  .leftside{
    height : 100%;
    width  : 62%;
  }
  .rightside{
    height : 100%;
    width  : 38%;
  }
  .vhcenter{
    display: flex;
    justify-content: center;
    align-items: center;
  }
  .vcenter{
    display: flex;
    align-items: center;
  }
  .namefont{
    font-size: 35px;
    color: rgb(0,191,255);
    margin-left: 5%;
    font-style: italic;
  }
  button{
    background-color: rgba(0,191,255,0.7);
  }
  a{
    text-decoration : none;
    font-size: 25px;
    //color: rgb(0,191,255);
    color : white;
  }
  ul{
    list-style-type : georgian;
  }
  .bgblue{
    background-color: rgba(0,191,255,0.7);
  }
  </style>
</head>
<body>
  <div class="mainbody">
    <div class="upperpart">
      <div class="leftside vcenter">
        <h2 class="namefont">{{username}}</h2>
      </div>
      <div class="rightside vhcenter">
        <button onclick="logout()">LOGOUT</button>
        <!--<a href="../logout">logout</a>-->
      </div>
    </div>
    <div class="downwardpart">
      <div class="leftside bgblue">
        <!--messages start-->
        <ul>
        {% for x in allaccount %}
        {% if x.username == username %}
        {% else %}

        {% for y in connections %}
          {% if y.token.token == token and y.ctoken == x.token %}
            <li><a href="{{token}}/{{x.token}}/messages/">{{ x.username }}</a></li>
          {% endif %}
        {% endfor %}
        {% endif %}
        {% endfor %}
        <ul>
        <!--messages end-->
      </div>
      <div class="rightside bgblue">
        <!--all users start-->
        <ul>
        {% for x in allaccount %}
        {% if x.username == username %}
        {% else %}
        <li><a href="{{token}}/{{x.token}}/messages/">{{ x.username }}</a></li>
        {% endif %}
        {% endfor %}
        <ul>
        <!--all users end-->
      </div>
    </div>
  </div>

<script>

function logout(){
  window.location.href="../logout"
}

</script>
</body>
</html>